# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              ""
baseurl:          /

markdown            : kramdown
highlighter         : rouge

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

hyde:
  # color scheme
  color: default #theme-base-08, theme-base-09, theme-base-0a
  #theme-base-0b, theme-base-0c, theme-base-0d, theme-base-0e
  #theme-base-0f
  # sidebar left or right
  sidebar: default #layout-reverse
  # sidebar fix or no
  sidebar-fix: sidebar-sticky#sidebar-nofix

plugins:
  - jekyll-gist
  - jekyll-paginate

paginate: 5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
